"""Canonical seed content for Vocably: words, topics, exams, decks.

Content is intentionally structured (normalized fields) rather than one big JSON
blob per word. This module is imported by server.py and used to (idempotently)
seed the database on startup.
"""

TOPICS = [
    {"slug": "academic", "name": "Academic Vocabulary", "icon": "school-outline", "description": "High-utility words for essays, lectures and research."},
    {"slug": "everyday", "name": "Everyday English", "icon": "coffee-outline", "description": "Words for daily conversation and life."},
    {"slug": "business", "name": "Business & Career", "icon": "briefcase-outline", "description": "Professional and workplace vocabulary."},
    {"slug": "science", "name": "Science & Nature", "icon": "flask-outline", "description": "Words from science, tech and the natural world."},
    {"slug": "emotions", "name": "Feelings & Emotions", "icon": "heart-outline", "description": "Describe moods, feelings and reactions precisely."},
    {"slug": "society", "name": "Society & Politics", "icon": "account-group-outline", "description": "Words about people, culture and government."},
]

EXAMS = [
    {"slug": "ielts", "name": "IELTS", "full_name": "International English Language Testing System", "category": "study_abroad", "score_type": "band", "max_score": 9.0, "description": "Academic and General Training English proficiency."},
    {"slug": "toefl", "name": "TOEFL", "full_name": "Test of English as a Foreign Language", "category": "study_abroad", "score_type": "points", "max_score": 120, "description": "Academic English for university admission."},
    {"slug": "gre", "name": "GRE", "full_name": "Graduate Record Examination", "category": "grad_school", "score_type": "points", "max_score": 340, "description": "High-level vocabulary for graduate admissions."},
    {"slug": "sat", "name": "SAT", "full_name": "Scholastic Assessment Test", "category": "undergrad", "score_type": "points", "max_score": 1600, "description": "College admission vocabulary and reading."},
    {"slug": "gmat", "name": "GMAT", "full_name": "Graduate Management Admission Test", "category": "grad_school", "score_type": "points", "max_score": 805, "description": "Business school verbal reasoning."},
    {"slug": "cefr", "name": "CEFR", "full_name": "Common European Framework A1–C2", "category": "general", "score_type": "level", "max_score": 6, "description": "Structured A1 to C2 English levels."},
]

# Each word: normalized fields + relationship lists (synonyms/antonyms/related
# reference other headwords by string; the knowledge graph is derived at seed time).
WORDS = [
    {
        "headword": "abate", "phonetic": "/əˈbeɪt/", "phonetic_us": "/əˈbeɪt/", "phonetic_uk": "/əˈbeɪt/",
        "part_of_speech": "verb", "cefr": "C1", "frequency": 3, "topic": "academic",
        "simple_definition": "to become less strong or intense", "easy_meaning": "become weaker",
        "detailed_definition": "To reduce in amount, degree, or intensity; to lessen.",
        "example": "The storm began to abate by morning.",
        "easy_example": "The rain started to abate.",
        "synonyms": ["diminish", "lessen", "subside"], "antonyms": ["intensify", "increase"],
        "related": ["diminish", "subside"], "word_family": ["abatement"],
        "roots": ["battre (to beat)"], "prefixes": ["a-"], "suffixes": [],
        "mnemonic": "A-BATE: the storm took the bait and calmed down.",
        "common_mistakes": "Do not confuse with 'abet' (to help someone do wrong).",
        "usage_notes": "Often used for storms, pain, noise and emotions.",
        "exam_relevance": ["gre", "sat", "toefl"], "academic_importance": 4,
    },
    {
        "headword": "ubiquitous", "phonetic": "/juːˈbɪkwɪtəs/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 3, "topic": "academic",
        "simple_definition": "present or found everywhere", "easy_meaning": "everywhere at once",
        "detailed_definition": "Existing or being everywhere at the same time; constantly encountered.",
        "example": "Smartphones have become ubiquitous in modern life.",
        "easy_example": "Coffee shops are ubiquitous in the city.",
        "synonyms": ["omnipresent", "pervasive", "universal"], "antonyms": ["rare", "scarce"],
        "related": ["pervasive"], "word_family": ["ubiquity"],
        "roots": ["ubique (everywhere)"], "prefixes": [], "suffixes": ["-ous"],
        "mnemonic": "You-BIQ: you seek it, it's already everywhere.",
        "common_mistakes": "Spelled with 'qui' not 'kwi'.",
        "usage_notes": "Formal; common in academic and journalistic writing.",
        "exam_relevance": ["gre", "sat", "ielts"], "academic_importance": 5,
    },
    {
        "headword": "pragmatic", "phonetic": "/præɡˈmætɪk/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "business",
        "simple_definition": "dealing with things sensibly and realistically", "easy_meaning": "practical, not idealistic",
        "detailed_definition": "Concerned with practical results rather than theories or ideals.",
        "example": "She took a pragmatic approach to solving the problem.",
        "easy_example": "Be pragmatic: pick the cheaper option.",
        "synonyms": ["practical", "realistic", "sensible"], "antonyms": ["idealistic", "impractical"],
        "related": ["practical"], "word_family": ["pragmatism", "pragmatist"],
        "roots": ["pragma (deed)"], "prefixes": [], "suffixes": ["-ic"],
        "mnemonic": "PRAG-matic people get practical things done.",
        "common_mistakes": "Not the same as 'dogmatic'.",
        "usage_notes": "Positive connotation in business contexts.",
        "exam_relevance": ["ielts", "toefl", "gmat"], "academic_importance": 4,
    },
    {
        "headword": "candid", "phonetic": "/ˈkændɪd/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "everyday",
        "simple_definition": "honest and direct", "easy_meaning": "truthful and open",
        "detailed_definition": "Truthful and straightforward; frank in expression.",
        "example": "He gave a candid account of the accident.",
        "easy_example": "Please be candid with me.",
        "synonyms": ["frank", "honest", "forthright"], "antonyms": ["evasive", "guarded"],
        "related": ["frank"], "word_family": ["candor", "candidly"],
        "roots": ["candidus (white, pure)"], "prefixes": [], "suffixes": [],
        "mnemonic": "A candid photo is unposed and honest.",
        "common_mistakes": "Do not confuse with 'candidate'.",
        "usage_notes": "Often 'candid about' something.",
        "exam_relevance": ["ielts", "sat"], "academic_importance": 3,
    },
    {
        "headword": "meticulous", "phonetic": "/məˈtɪkjələs/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 3, "topic": "academic",
        "simple_definition": "very careful and precise", "easy_meaning": "extremely careful",
        "detailed_definition": "Showing great attention to detail; very careful and precise.",
        "example": "The scientist kept meticulous records of every experiment.",
        "easy_example": "She is meticulous about her work.",
        "synonyms": ["thorough", "scrupulous", "precise"], "antonyms": ["careless", "sloppy"],
        "related": ["thorough"], "word_family": ["meticulously", "meticulousness"],
        "roots": ["meticulosus (fearful)"], "prefixes": [], "suffixes": ["-ous"],
        "mnemonic": "Meticulous = 'me' + 'ticks' every box.",
        "common_mistakes": "Positive word; do not use for over-worrying.",
        "usage_notes": "Common with 'records', 'planning', 'detail'.",
        "exam_relevance": ["ielts", "toefl", "gre"], "academic_importance": 4,
    },
    {
        "headword": "resilient", "phonetic": "/rɪˈzɪliənt/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "emotions",
        "simple_definition": "able to recover quickly from difficulties", "easy_meaning": "bounces back",
        "detailed_definition": "Able to withstand or recover quickly from difficult conditions.",
        "example": "Children are often remarkably resilient.",
        "easy_example": "He stayed resilient after the setback.",
        "synonyms": ["tough", "adaptable", "hardy"], "antonyms": ["fragile", "vulnerable"],
        "related": ["adaptable"], "word_family": ["resilience"],
        "roots": ["resilire (to jump back)"], "prefixes": ["re-"], "suffixes": ["-ent"],
        "mnemonic": "A resilient band snaps back into shape.",
        "common_mistakes": "Spelled 'resilient', not 'resiliant'.",
        "usage_notes": "Used for people, materials and systems.",
        "exam_relevance": ["ielts", "toefl"], "academic_importance": 4,
    },
    {
        "headword": "concise", "phonetic": "/kənˈsaɪs/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "academic",
        "simple_definition": "giving a lot of information clearly in few words", "easy_meaning": "short and clear",
        "detailed_definition": "Expressing much in few words; brief but comprehensive.",
        "example": "Her report was concise and easy to follow.",
        "easy_example": "Keep your answer concise.",
        "synonyms": ["brief", "succinct", "compact"], "antonyms": ["verbose", "lengthy"],
        "related": ["succinct"], "word_family": ["concisely", "conciseness"],
        "roots": ["concidere (to cut up)"], "prefixes": ["con-"], "suffixes": ["-ise"],
        "mnemonic": "Concise = precise cutting of extra words.",
        "common_mistakes": "Not the same as 'precise'.",
        "usage_notes": "Praise for clear, short writing.",
        "exam_relevance": ["ielts", "toefl", "gmat"], "academic_importance": 4,
    },
    {
        "headword": "ambiguous", "phonetic": "/æmˈbɪɡjuəs/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 3, "topic": "academic",
        "simple_definition": "having more than one possible meaning", "easy_meaning": "unclear, two meanings",
        "detailed_definition": "Open to more than one interpretation; not having one clear meaning.",
        "example": "The instructions were ambiguous and confused everyone.",
        "easy_example": "His answer was ambiguous.",
        "synonyms": ["vague", "unclear", "equivocal"], "antonyms": ["clear", "explicit"],
        "related": ["vague"], "word_family": ["ambiguity", "ambiguously"],
        "roots": ["ambi- (both)", "agere (to drive)"], "prefixes": ["ambi-"], "suffixes": ["-ous"],
        "mnemonic": "Ambiguous points 'both' ways.",
        "common_mistakes": "Different from 'ambivalent' (mixed feelings).",
        "usage_notes": "Common in analysis of texts and rules.",
        "exam_relevance": ["gre", "sat", "toefl"], "academic_importance": 5,
    },
    {
        "headword": "diligent", "phonetic": "/ˈdɪlɪdʒənt/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "everyday",
        "simple_definition": "working hard and carefully", "easy_meaning": "hard-working",
        "detailed_definition": "Showing care and conscientious effort in one's work or duties.",
        "example": "A diligent student reviews notes every day.",
        "easy_example": "She is diligent about homework.",
        "synonyms": ["hardworking", "industrious", "conscientious"], "antonyms": ["lazy", "negligent"],
        "related": ["industrious"], "word_family": ["diligence", "diligently"],
        "roots": ["diligere (to value)"], "prefixes": [], "suffixes": ["-ent"],
        "mnemonic": "Diligent people 'deal-a-gent-ly' with tasks daily.",
        "common_mistakes": "Spelled with one 'l'.",
        "usage_notes": "Common in school and work praise.",
        "exam_relevance": ["ielts", "sat"], "academic_importance": 3,
    },
    {
        "headword": "inevitable", "phonetic": "/ɪnˈevɪtəbl/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "everyday",
        "simple_definition": "certain to happen; unavoidable", "easy_meaning": "sure to happen",
        "detailed_definition": "Certain to happen and impossible to prevent or avoid.",
        "example": "Change is inevitable in any growing company.",
        "easy_example": "Losing sometimes is inevitable.",
        "synonyms": ["unavoidable", "certain", "inescapable"], "antonyms": ["avoidable", "uncertain"],
        "related": ["unavoidable"], "word_family": ["inevitably", "inevitability"],
        "roots": ["evitare (to avoid)"], "prefixes": ["in-"], "suffixes": ["-able"],
        "mnemonic": "IN-EVITABLE: you cannot 'evite' (avoid) it.",
        "common_mistakes": "Spelled 'inevitable', not 'unevitable'.",
        "usage_notes": "Often 'it was inevitable that...'.",
        "exam_relevance": ["ielts", "toefl", "gmat"], "academic_importance": 4,
    },
    {
        "headword": "scrutinize", "phonetic": "/ˈskruːtənaɪz/", "part_of_speech": "verb", "cefr": "C1",
        "frequency": 3, "topic": "academic",
        "simple_definition": "to examine something very carefully", "easy_meaning": "look at closely",
        "detailed_definition": "To examine or inspect closely and thoroughly.",
        "example": "Investors scrutinize every line of the report.",
        "easy_example": "The teacher scrutinized my essay.",
        "synonyms": ["examine", "inspect", "analyze"], "antonyms": ["ignore", "skim"],
        "related": ["examine"], "word_family": ["scrutiny"],
        "roots": ["scrutari (to search)"], "prefixes": [], "suffixes": ["-ize"],
        "mnemonic": "Screw-tin-eyes: eyes searching every tin.",
        "common_mistakes": "US spelling 'scrutinize', UK 'scrutinise'.",
        "usage_notes": "Formal; common with documents and data.",
        "exam_relevance": ["gre", "gmat", "toefl"], "academic_importance": 5,
    },
    {
        "headword": "eloquent", "phonetic": "/ˈeləkwənt/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 3, "topic": "society",
        "simple_definition": "fluent and persuasive in speaking or writing", "easy_meaning": "speaks beautifully",
        "detailed_definition": "Expressing ideas clearly, fluently and persuasively.",
        "example": "She gave an eloquent speech about justice.",
        "easy_example": "He is an eloquent speaker.",
        "synonyms": ["articulate", "expressive", "fluent"], "antonyms": ["inarticulate", "tongue-tied"],
        "related": ["articulate"], "word_family": ["eloquence", "eloquently"],
        "roots": ["eloqui (to speak out)"], "prefixes": ["e-"], "suffixes": ["-ent"],
        "mnemonic": "Elo-QUENT: quite quaint, quality talk.",
        "common_mistakes": "Not just loud — it means well-spoken.",
        "usage_notes": "Praise for speakers and writers.",
        "exam_relevance": ["sat", "gre", "ielts"], "academic_importance": 4,
    },
    {
        "headword": "tenacious", "phonetic": "/təˈneɪʃəs/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 2, "topic": "emotions",
        "simple_definition": "holding firmly to a goal; persistent", "easy_meaning": "never gives up",
        "detailed_definition": "Not readily letting go; persistent and determined.",
        "example": "Her tenacious effort finally paid off.",
        "easy_example": "Be tenacious and keep trying.",
        "synonyms": ["persistent", "determined", "dogged"], "antonyms": ["irresolute", "yielding"],
        "related": ["persistent"], "word_family": ["tenacity", "tenaciously"],
        "roots": ["tenere (to hold)"], "prefixes": [], "suffixes": ["-ous"],
        "mnemonic": "Ten-acious: holds on with all ten fingers.",
        "common_mistakes": "Positive quality, not stubbornness.",
        "usage_notes": "Common with 'effort', 'grip', 'spirit'.",
        "exam_relevance": ["gre", "sat"], "academic_importance": 4,
    },
    {
        "headword": "coherent", "phonetic": "/kəʊˈhɪərənt/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "academic",
        "simple_definition": "logical and well organized", "easy_meaning": "makes sense together",
        "detailed_definition": "Logically connected, consistent and easy to understand.",
        "example": "He presented a coherent argument.",
        "easy_example": "Write a coherent paragraph.",
        "synonyms": ["logical", "consistent", "clear"], "antonyms": ["incoherent", "disjointed"],
        "related": ["logical"], "word_family": ["coherence", "coherently"],
        "roots": ["cohaerere (to stick together)"], "prefixes": ["co-"], "suffixes": ["-ent"],
        "mnemonic": "Co-HERE-nt: all ideas cohere here.",
        "common_mistakes": "Different from 'cohesive'.",
        "usage_notes": "Key for IELTS/TOEFL writing scores.",
        "exam_relevance": ["ielts", "toefl", "gmat"], "academic_importance": 5,
    },
    {
        "headword": "novice", "phonetic": "/ˈnɒvɪs/", "part_of_speech": "noun", "cefr": "B1",
        "frequency": 4, "topic": "everyday",
        "simple_definition": "a person new to and inexperienced in something", "easy_meaning": "a beginner",
        "detailed_definition": "A person who is new to and inexperienced in a job or situation.",
        "example": "As a novice, she asked many questions.",
        "easy_example": "I'm a novice at chess.",
        "synonyms": ["beginner", "newcomer", "learner"], "antonyms": ["expert", "veteran"],
        "related": ["beginner"], "word_family": ["novel"],
        "roots": ["novus (new)"], "prefixes": [], "suffixes": ["-ice"],
        "mnemonic": "NOV = new. A novice is new.",
        "common_mistakes": "It's a noun, not an adjective.",
        "usage_notes": "Neutral; common in learning contexts.",
        "exam_relevance": ["ielts", "sat"], "academic_importance": 2,
    },
    {
        "headword": "abundant", "phonetic": "/əˈbʌndənt/", "part_of_speech": "adjective", "cefr": "B1",
        "frequency": 5, "topic": "science",
        "simple_definition": "existing in large quantities; plentiful", "easy_meaning": "a lot of",
        "detailed_definition": "Present in great quantity; more than enough.",
        "example": "The region has abundant natural resources.",
        "easy_example": "Water is abundant here.",
        "synonyms": ["plentiful", "ample", "copious"], "antonyms": ["scarce", "sparse"],
        "related": ["plentiful"], "word_family": ["abundance", "abundantly"],
        "roots": ["abundare (to overflow)"], "prefixes": ["ab-"], "suffixes": ["-ant"],
        "mnemonic": "A-BUNDANT: a bundle and a ton — plenty!",
        "common_mistakes": "Spelled with 'un', not 'on'.",
        "usage_notes": "Common with resources and supply.",
        "exam_relevance": ["ielts", "toefl", "sat"], "academic_importance": 3,
    },
    {
        "headword": "deteriorate", "phonetic": "/dɪˈtɪəriəreɪt/", "part_of_speech": "verb", "cefr": "B2",
        "frequency": 4, "topic": "science",
        "simple_definition": "to become progressively worse", "easy_meaning": "get worse",
        "detailed_definition": "To become progressively worse in quality or condition.",
        "example": "His health began to deteriorate rapidly.",
        "easy_example": "The weather deteriorated.",
        "synonyms": ["worsen", "decline", "degrade"], "antonyms": ["improve", "recover"],
        "related": ["decline"], "word_family": ["deterioration"],
        "roots": ["deterior (worse)"], "prefixes": ["de-"], "suffixes": ["-ate"],
        "mnemonic": "De-TERROR-iorate: terror makes things worse.",
        "common_mistakes": "Spelled 'deteriorate', not 'deteriate'.",
        "usage_notes": "Common with health, weather, relations.",
        "exam_relevance": ["ielts", "toefl", "gre"], "academic_importance": 4,
    },
    {
        "headword": "advocate", "phonetic": "/ˈædvəkeɪt/", "part_of_speech": "verb", "cefr": "B2",
        "frequency": 4, "topic": "society",
        "simple_definition": "to publicly support a cause or policy", "easy_meaning": "to support strongly",
        "detailed_definition": "To publicly recommend or support a particular cause or policy.",
        "example": "She advocates for equal education.",
        "easy_example": "They advocate healthy eating.",
        "synonyms": ["support", "champion", "endorse"], "antonyms": ["oppose", "discourage"],
        "related": ["champion"], "word_family": ["advocacy", "advocacy"],
        "roots": ["vocare (to call)"], "prefixes": ["ad-"], "suffixes": ["-ate"],
        "mnemonic": "Ad-VOCATE: you give voice (voce) to a cause.",
        "common_mistakes": "Verb stressed 'AD-vo-cate', noun same spelling.",
        "usage_notes": "Often 'advocate for' something.",
        "exam_relevance": ["ielts", "toefl", "gmat"], "academic_importance": 4,
    },
    {
        "headword": "prudent", "phonetic": "/ˈpruːdnt/", "part_of_speech": "adjective", "cefr": "C1",
        "frequency": 3, "topic": "business",
        "simple_definition": "acting with care and thought for the future", "easy_meaning": "wisely careful",
        "detailed_definition": "Showing care and good judgement about the future.",
        "example": "It is prudent to save for emergencies.",
        "easy_example": "A prudent choice saved money.",
        "synonyms": ["wise", "cautious", "sensible"], "antonyms": ["reckless", "rash"],
        "related": ["cautious"], "word_family": ["prudence", "prudently"],
        "roots": ["providens (foreseeing)"], "prefixes": [], "suffixes": ["-ent"],
        "mnemonic": "PRU-dent makes a small dent, not a crash.",
        "common_mistakes": "Different from 'prudish'.",
        "usage_notes": "Common in finance and planning.",
        "exam_relevance": ["gre", "gmat", "sat"], "academic_importance": 4,
    },
    {
        "headword": "spontaneous", "phonetic": "/spɒnˈteɪniəs/", "part_of_speech": "adjective", "cefr": "B2",
        "frequency": 4, "topic": "emotions",
        "simple_definition": "happening naturally without planning", "easy_meaning": "sudden, unplanned",
        "detailed_definition": "Performed or occurring as a result of a sudden impulse, without planning.",
        "example": "They made a spontaneous decision to travel.",
        "easy_example": "We took a spontaneous trip.",
        "synonyms": ["impulsive", "unplanned", "instinctive"], "antonyms": ["planned", "deliberate"],
        "related": ["impulsive"], "word_family": ["spontaneity", "spontaneously"],
        "roots": ["sponte (of one's own accord)"], "prefixes": [], "suffixes": ["-ous"],
        "mnemonic": "Spon-TAN-eous: like getting a tan on a whim.",
        "common_mistakes": "Spelled with 'ta', not 'te'.",
        "usage_notes": "Positive for people, neutral for events.",
        "exam_relevance": ["ielts", "toefl"], "academic_importance": 3,
    },
]
