-- ============================================================
-- MIGRATION 005: AI Coach & TTS Cache Tables
-- Project  : Vocabist → Supabase
-- Purpose  : Store AI Coach generated content, daily usage
--            tracking, and TTS audio cache.
-- Safety   : Non-destructive. Uses CREATE TABLE IF NOT EXISTS.
-- Depends  : Migration 002 (words), Migration 003 (users)
-- Run via  : Supabase Dashboard → SQL Editor
--
-- NOTE ON TTS AUDIO STORAGE:
--   TTS audio is stored as BYTEA (binary) in PostgreSQL,
--   directly equivalent to MongoDB BSON Binary.
--   Current audio files are ~8–50 KB each (TTS mp3 snippets).
--   For large-scale production use, consider migrating BYTEA
--   to object storage (Supabase Storage) in a future phase.
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 005a. ai_coach_content
--   MongoDB: db.ai_coach_content  (4 docs at audit time)
--
--   One cached AI Coach response per word (word_id is unique).
--   Content is a small fixed-key dict → JSONB.
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ai_coach_content (
    id          BIGSERIAL   PRIMARY KEY,
    word_id     TEXT        NOT NULL UNIQUE REFERENCES public.words(id) ON DELETE CASCADE,

    content     JSONB       NOT NULL,
    -- { explanation: str, example: str, mnemonic: str }
    -- Generated by GPT-5.6-Luna via /api/words/{word_id}/ai-coach

    provenance  TEXT        NOT NULL DEFAULT 'ai_generated',
    status      TEXT        NOT NULL DEFAULT 'PUBLISHED',

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ai_coach_content_status_check
        CHECK (status IN ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'))
);

COMMENT ON TABLE  public.ai_coach_content IS 'Cached AI Coach explanations per word. Generated by GPT-5.6-Luna on first request, served from cache on subsequent requests.';
COMMENT ON COLUMN public.ai_coach_content.content IS 'JSONB: { explanation, example, mnemonic }. All three keys always present for PUBLISHED rows.';
COMMENT ON COLUMN public.ai_coach_content.word_id IS 'One AI Coach entry per word (UNIQUE constraint). Matches words.id.';

-- ────────────────────────────────────────────────────────────
-- 005b. ai_coach_usage
--   MongoDB: db.ai_coach_usage  (4 docs at audit time)
--
--   Daily per-user usage counter for the AI Coach rate limit
--   (free tier: 3 per day, pro: unlimited).
--   date column enables efficient same-day counting:
--     SELECT COUNT(*) FROM ai_coach_usage
--     WHERE user_id = $1 AND date = CURRENT_DATE
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ai_coach_usage (
    id          BIGSERIAL   PRIMARY KEY,
    user_id     TEXT        NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    word_id     TEXT        NOT NULL REFERENCES public.words(id)      ON DELETE CASCADE,
    date        DATE        NOT NULL DEFAULT CURRENT_DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.ai_coach_usage IS 'Per-user daily AI Coach usage log. Used for rate limiting: free=3/day, pro=unlimited.';
COMMENT ON COLUMN public.ai_coach_usage.date IS 'ISO date (DATE type). Query: WHERE user_id=$1 AND date=CURRENT_DATE for daily count.';

-- ────────────────────────────────────────────────────────────
-- 005c. tts_cache
--   MongoDB: db.tts_cache  (1 doc at audit time)
--
--   Cached TTS mp3 audio keyed by SHA-256 of the input text +
--   voice parameters. Prevents regenerating the same audio.
--
--   key = sha256("{text}|{voice}|{speed}|{model}|{format}")
--   e.g. sha256("abate|alloy|1.0|tts-1|mp3")
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tts_cache (
    key         TEXT        PRIMARY KEY,
    -- SHA-256 hex digest of: "{text}|{voice}|{speed}|{model}|{format}"
    -- e.g. "f8e2e038d506482b42f687af84d5e4d767..." (64 hex chars)

    audio       BYTEA       NOT NULL,
    -- Raw mp3 bytes. Served directly via GET /api/tts/{key}.mp3
    -- Direct MongoDB BSON Binary → PostgreSQL BYTEA mapping.
    -- Current size: ~8–50 KB per entry (word-level TTS snippets)

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.tts_cache IS 'TTS audio cache keyed by SHA-256 of text+voice params. Audio stored as BYTEA (~8–50 KB per entry).';
COMMENT ON COLUMN public.tts_cache.key IS 'SHA-256 hex of "{text}|{voice}|{speed}|{model}|{format}". Matches Python hashlib.sha256(...).hexdigest().';
COMMENT ON COLUMN public.tts_cache.audio IS 'Raw mp3 bytes from OpenAI TTS API. Served as audio/mpeg by /api/tts/{key}.mp3.';
