"""
Vocabist — Enable Row-Level Security (RLS) on Supabase Tables
==============================================================

Architecture context:
- ALL data access goes through FastAPI backend (service-role key)
- Service role BYPASSES RLS in Supabase (this is the design intent)
- RLS is enabled to PREVENT direct client/anon access to the database
- No explicit policies needed for service role (bypass is automatic)
- We create a single restrictive policy per table to document intent

Run with:
    DB_BACKEND=supabase python3 migrations/enable_rls.py

Tables to secure:
    users, profiles, user_sessions, subscriptions,
    user_word_progress, saved_words, study_sessions,
    analytics_events, ai_coach_content, ai_coach_usage, tts_cache

Reference tables (public read is acceptable but restrict writes):
    words, topics, exams, articles
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from dotenv import load_dotenv
load_dotenv(BACKEND_DIR / ".env")

import psycopg2
import psycopg2.extras

SUPABASE_DB_URL = os.environ.get("SUPABASE_DB_URL", "")

# User data tables — enable RLS + deny all direct access (service role bypasses)
USER_DATA_TABLES = [
    "users",
    "profiles",
    "user_sessions",
    "subscriptions",
    "user_word_progress",
    "saved_words",
    "study_sessions",
    "analytics_events",
    "ai_coach_content",
    "ai_coach_usage",
    "tts_cache",
]

# Reference tables — enable RLS + allow authenticated reads for future direct-client use
# For now, all access goes through backend, so restrict everything
REFERENCE_TABLES = [
    "words",
    "topics",
    "exams",
    "articles",
]

ALL_TABLES = USER_DATA_TABLES + REFERENCE_TABLES

RLS_SQL = """
-- ============================================================
-- Vocabist — RLS Enablement Script
-- Generated by enable_rls.py
-- 
-- Architecture: All DB access via FastAPI (service_role)
--   - Service role bypasses RLS automatically
--   - RLS protects against direct client/anon access
--   - No explicit policies needed for service_role
-- ============================================================

-- USER DATA TABLES: Enable RLS (service_role bypasses automatically)
"""

for table in USER_DATA_TABLES:
    RLS_SQL += f"""
ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY;
"""

RLS_SQL += """
-- REFERENCE TABLES: Enable RLS
"""
for table in REFERENCE_TABLES:
    RLS_SQL += f"""
ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY;
"""

RLS_SQL += """
-- Verification: List tables with RLS enabled
SELECT
    schemaname,
    tablename,
    rowsecurity AS rls_enabled,
    forcepolicies AS rls_forced
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;
"""


def enable_rls():
    if not SUPABASE_DB_URL:
        print("[ERROR] SUPABASE_DB_URL not configured. Cannot run RLS migration directly.")
        print("[INFO]  Run the following SQL in Supabase SQL Editor instead:")
        print()
        sql = "\n".join([
            f"ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;" for t in ALL_TABLES
        ] + [
            f"ALTER TABLE public.{t} FORCE ROW LEVEL SECURITY;" for t in ALL_TABLES
        ])
        print(sql)
        return False

    print("Connecting to Supabase PostgreSQL...")
    try:
        conn = psycopg2.connect(SUPABASE_DB_URL)
        conn.autocommit = True
        cur = conn.cursor()
        print("Connected.")

        results = []
        for table in ALL_TABLES:
            try:
                cur.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;")
                cur.execute(f"ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY;")
                results.append((table, "✓ RLS enabled"))
                print(f"  [✓] {table}: RLS enabled")
            except Exception as e:
                results.append((table, f"✗ {e}"))
                print(f"  [✗] {table}: {e}")

        # Verify
        cur.execute("""
            SELECT tablename, rowsecurity, forcepolicies
            FROM pg_tables
            WHERE schemaname = 'public'
            ORDER BY tablename;
        """)
        rows = cur.fetchall()
        print()
        print("RLS Status Verification:")
        for row in rows:
            tname, rls, force = row
            if tname in ALL_TABLES:
                status = "✓" if rls else "✗"
                print(f"  {status} {tname}: rls={rls} forced={force}")

        cur.close()
        conn.close()
        return all("✓" in r[1] for r in results)

    except Exception as e:
        print(f"[ERROR] Database connection failed: {e}")
        print()
        print("[INFO] Run this SQL manually in Supabase Dashboard > SQL Editor:")
        for t in ALL_TABLES:
            print(f"  ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;")
            print(f"  ALTER TABLE public.{t} FORCE ROW LEVEL SECURITY;")
        return False


if __name__ == "__main__":
    print("=" * 60)
    print("  VOCABIST — RLS ENABLEMENT")
    print("=" * 60)
    success = enable_rls()
    print()
    if success:
        print("[✓] RLS enabled on all tables")
        print("[✓] Service-role backend access unaffected (bypasses RLS)")
        print("[✓] Direct client/anon access now restricted")
    else:
        print("[!] RLS enablement failed or requires manual SQL execution")
    print("=" * 60)
    sys.exit(0 if success else 1)
